### ISSUE TITLE
Permission to Publish the Unix Tools

### ISSUE THREAD

**Issue by tajmone** [ChrisRfr/purebasic#6]
Hi @ChrisRfr, I haven't heard from you since the Christmas holidays break. I'd like to make the Unix tools for Windows available as an alternative to UnxUtils, and close fantaisie-software/purebasic#30.

Is it OK with you if I go ahead and publish the binary tools that you've gathered as a ZIP archive at the PureBasic upstream Wiki, adding a README file with the description of the contents and crediting you for its creation?

**Comment by ChrisRfr** [comment]
Hi tajmone, 
Of course you can publish, I'd even say, Finally. That's why I did it

I wanted to participate more in the PureBasic IDE OpenSource Projects
but apart from you, there was no sign of interest in my small contributions or the work of some others.
kenmo wrote about the same preoccupations, later on the forum, here
https://www.purebasic.fr/english/viewtopic.php?p=548049#p548049

Sorry, I'm not angry, but Without a project team spirit and without any sign of interest, I saw no reason to give more of my free time
I preferred to continue developing my SweetyVD project
The new engine I'm developing is very promising, really.
There's still work to be done, but I think it can be really superior to Pureform, With much respect for Polo's work.
But, here too, not much sign of interest. it's me! disappointing

**Comment by tajmone** [comment]
Sorry for the misunderstanding, I was waiting for you to reply to my PRs and Issue on your repo, and just thought you were busy (you mentioned something about studies tight schedules, if I remember correctly), so I didn't nagger you about it.

> Of course you can publish, I'd even say, Finally. That's why I did it

It's just that I didn't want to overstep you, after all you did all the work here, so I was in "waiting mode". No big deal.

> I wanted to participate more in the PureBasic IDE OpenSource Projects
but apart from you, there was no sign of interest in my small contributions or the work of some others.

The holiday breaks were longer than expected, but a couple of weeks ago all activities have resumed, after a long silence, and now we're witnessing a constant flux of contributions.

Rarely open source projects have a fast pace, unless they are financially backed by some big industry that pays wages to its maintainers (something you can apply for via GitHub sponsors program). Most projects are run on a voluntary basis, with people contributing in their spare time (which is usually very little, and spread thin across multiple projects).

Also, I think that this year the season flue hit many people sick — I got sick during the last days of December and haven't still recovered completely! This year the flue was really bad, and I suffered severe kidney pains that locked me in bed for weeks. This might be a significant factor in many projects having slowed down in the last months (the media speak of a flue pandemic, and different countries have been affected to different degrees).

> I preferred to continue developing my SweetyVD project

That's always a good idea, giving priority to your own projects. After all, if you don't look after your projects who else will? :wink:

I'll buzz you when the ZIP archive is published.

**Comment by tajmone** [comment]
Published! Please check:

https://github.com/fantaisie-software/purebasic/issues/30#issuecomment-589732228

**Comment by ChrisRfr** [comment]
Thanks tajmone

**Comment by tajmone** [comment]
All taken care of (see fantaisie-software/purebasic#72)
